### PR TITLE
Support for Rebar3

### LINKED ISSUE #20: rebar3 do not compile sext
Hello, Ulf!

Rebar3 do not compile sext. 
The reasons are: lack of src dir and not working C interface.

### PR DESCRIPTION
**Pull request by contented**
Greetings, Ulf!

add rebar.config.script with options for rebar3
resolve #20

### CODE REVIEW

**Comment by uwiger** [comment]
I have no problem with adding a rebar.config.script to address rebar3 support, but I would like to know how to reproduce the problem. Could you describe the steps required to reproduce?

**Comment by contented** [comment]
I have rebar 3.1.0 on Erlang/OTP 17 Erts 6.4 on both MacOS and Ubuntu
I do (on branch master):

**$** git clone git@github.com:uwiger/sext.git
**$** rebar3 compile
```
===> Verifying dependencies...
===> Fetching edown ({git,"git://github.com/uwiger/edown.git","HEAD"})
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref}, otherwise updating the dep may not work as expected.
===> Compiling edown
===> Compiling sext
```
**$** ls 

> Here I have problem N1 - C code doesn't compile. (No priv dir)

```
LICENSE		README.md	examples	rebar.lock	vsn.mk
Makefile	_build		rebar		src
NOTICE		doc		rebar.config	test
```
**$** ls _build/default/lib/sext/ebin/

> Here I have problem N2 - Rebar3 doesn't see the src dir.

`sext.app	tt_proto.beam`

**$** cd _build/default/lib/sext/
**$** ls -l
```
total 24
drwxr-xr-x  4 oleg  staff  136 26 апр 01:25 ebin
lrwxr-xr-x  1 oleg  staff   20 26 апр 01:23 examples -> ../../../../examples
lrwxr-xr-x  1 oleg  staff   19 26 апр 01:23 include -> ../../../../include
lrwxr-xr-x  1 oleg  staff   16 26 апр 01:23 priv -> ../../../../priv
```

**Comment by uwiger** [comment]
Thanks. Sorry for the delay, but I've managed to reproduce it and verified your fix. Merged.

**Comment by contented** [comment]
Great! Ulf, thank you for your time.

**Pull request merged**
